[colors.bright]
black = "#46525c"   
blue = "#95B2D6"    
cyan = "#5fb4b4"    
green = "#99c794"   
magenta = "#cc8ec6" 
red = "#f97b58"     
white = "#ffffff"   
yellow = "#fac761"  

[colors.dim]
black = "#333333"
blue = "#6699cc"
cyan = "#66cccc"
green = "#99cc99"
magenta = "#cc99cc"
red = "#f2777a"
white = "#dddddd"
yellow = "#ffcc66"

[colors.normal]
black = "#3b454e" 
blue = "#95B2D6"  
cyan = "#5fb4b4"  
green = "#99c794" 
magenta = "#edacfd"
red = "#ec5f66"   
white = "#f7f7f7" 
yellow = "#f9ae58"

[colors.primary]
background = "#2e363e"
foreground = "#d8dee9"
