#!/bin/sh

export XDG_STATE_HOME=${XDG_STATE_HOME:-$HOME/.local/state}
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}

mkdir -p ${XDG_STATE_HOME}/darkman
echo 0 > "${XDG_STATE_HOME}/darkman/darkmode"

# GTK
if pgrep -x xsettingsd >/dev/null 2>&1; then
  sed --in-place --follow-symlinks 's/\(Net\/\(Icon\)\?ThemeName "\(Papirus\|Arc\)\)-Dark"/\1"/' "${XDG_CONFIG_HOME}/xsettingsd"
  systemctl --user restart xsettingsd
fi

# Alacritty
sed --in-place --follow-symlinks 's/colors\/.*\.toml/colors\/seoul256-light.toml/' "${XDG_CONFIG_HOME}/alacritty/alacritty.toml"

# nvim

# tmux
tmux set-option -g status-bg darkgrey
